import sys
from datetime import datetime
from lib.utils.data import fileproc
from lib.utils.misc.pathresolver import acrp
from google import protobuf

# Make sure that caffe is on the python path:
sys.path.append(acrp('python'))
from caffe.proto import caffe_pb2


def parse_solver_file(filepath):
    '''
    Returns a protobuf object with the solver parameters
    '''
    lines = fileproc.freadlines(filepath)
    return parse_solver_file_content('\n'.join(lines))


def parse_solver_file_content(file_content):
    '''
    Returns a protobuf object with the solver parameters
    '''
    solver_params = caffe_pb2.SolverParameter()
    protobuf.text_format.Merge(file_content, solver_params)

    return solver_params


def save_protobuf_file(filepath, protobuf_params):
    '''
    Saves a protobuf file using the specified parameters
    '''
    with open(filepath, 'w') as f:
        f.write('# GENERATED BY TRAINER.PY {0}\n'.format(datetime.now()))
        f.write(protobuf.text_format.MessageToString(protobuf_params))


def parse_model_definition_file(filepath):
    '''
    Parse protobuf file
    '''
    lines = fileproc.freadlines(filepath)
    return parse_model_definition_file_content('\n'.join(lines))


def parse_model_definition_file_content(file_content):
    '''
    Parse protobuf file content
    '''
    model_params = caffe_pb2.NetParameter()
    protobuf.text_format.Merge(file_content, model_params)

    return model_params


