import sys
from datetime import datetime
from lib.utils.data import fileproc
from lib.utils.misc.pathresolver import acrp
from google import protobuf

# Make sure that caffe is on the python path:
sys.path.append(acrp('python'))
from caffe.proto import caffe_pb2


def parse_solver_file(filepath):
    '''
    Returns a protobuf object with the solver parameters
    '''
    lines = fileproc.freadlines(filepath)
    solver_params = caffe_pb2.SolverParameter()
    protobuf.text_format.Merge('\n'.join(lines), solver_params)

    return solver_params


def save_solver_file(filepath, solver_params):
    '''
    Saves a solver file using the specified parameters
    '''
    with open(filepath, 'w') as f:
        f.write('# GENERATED BY TRAINER.PY {0}\n'.format(datetime.now()))
        f.write(protobuf.text_format.MessageToString(solver_params))


def parse_model_definition_file(filepath):
    '''
    Parse protobuf file
    '''
    lines = fileproc.freadlines(filepath)
    model_params = caffe_pb2.NetParameter()
    protobuf.text_format.Merge('\n'.join(lines), model_params)

    return model_params


